### PR TITLE
correcting the midi notes

### PR DESCRIPTION
**Pull request by ErinaceusLinnaeus**
Midi note correction for #27

### CODE REVIEW

**Comment by momentarylapse** [comment]
Nice!

Could you also update the comments in those 2 lines (C2 -> C3 etc)?

Btw. pitch names are annoying, with multiple inconsistent conventions. Tsunami tries to stick to "scientific notation". I double checked the code and this handy [chart](https://en.wikipedia.org/wiki/Scientific_pitch_notation#Table_of_note_frequencies)

**Comment by ErinaceusLinnaeus** [comment]
The comments were and are correct, according to the chart I found. Also the manual and the web-interface of the Mandala use it as it is commented right now.

Following your scientific chart it would be C3 -> F3 for the zones and C4 -> C5, C6 for the rims.

**Comment by momentarylapse** [comment]
Tricky...

After some more googling, I think most people dealing with midi call pitch 48 "C3". That is also the tsunami convention. Probably Mandala uses a less common convention in their documentation?

I'd like to stay consistent within tsunami (including the MidiDebugger). Would it be ok for you, to write for the surfaces something like this?
```
let SURFACE_PITCHES = [48, 50, 52, 53] # C3,D3,E3,F3
# warning: Mandala calls these C2,D2,E2,F2
```

The comment targets tsunami/midi developers. And in the UI, we will try to avoid mentioning any names.

**Comment by ErinaceusLinnaeus** [comment]
Ready to merge

**Pull request merged**
